version: '3'

services:     #service is the name of the service, in this case,proxy and web respectively.
  proxy:      #All services must either have an image or build key.
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # this will use httpd:latest
